//
//
/*!
  \file
  \ingroup IO
  \brief Declaration of class stir::InputStreamFromSimSET

  \author Nikos Efthimiou

*/
/*
    Copyright (C) 2019, University of Hull
    This file is part of STIR.

    This file is free software; you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation; either version 2.1 of the License, or
    (at your option) any later version.

    This file is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    See STIR/LICENSE.txt for details
*/

#ifndef __stir_IO_InputStreamFromSimSET_H__
#define __stir_IO_InputStreamFromSimSET_H__

#include "stir/shared_ptr.h"
#include "stir/Succeeded.h"
#include "stir/listmode/CListRecordSimSET.h"
#include "stir/RegisteredParsingObject.h"

#include <iostream>
#include <string>
#include <vector>

extern "C" {
#include "SystemDependent.h"

#include "LbTypes.h"
#include "LbError.h"
#include "LbDebug.h"
#include "LbEnvironment.h"
#include "LbFile.h"
#include "LbMemory.h"
#include "LbParamFile.h"
#include "LbInterface.h"
#include "LbHeader.h"

#include "Photon.h"
#include "PhgParams.h"
#include "ColTypes.h"
#include "ColParams.h"
#include "DetTypes.h"
#include "DetParams.h"
#include "CylPos.h"
#include "PhgMath.h"
#include "PhoHFile.h"
#include "PhgHdr.h"
#include "ProdTbl.h"
#include "PhoTrk.h"
#include "SubObj.h"
#include "EmisList.h"
#include "Collimator.h"
#include "Detector.h"
#include "phg.h"
#include "PhgBin.h"

#include <PhoHFile.h>
}

/* LOCAL TYPES */
typedef enum  {Null, Decay, Photon} EventTy;

START_NAMESPACE_STIR


/*! 
 * \brief A helper class to read data from a SimSET history file
 * \author Nikos Efthimiou
 *
 * \details This class is responsible for reading photons from a PGH history
 * file generated by SimSET.
 *
 *
 * Large parts of the functions are adaptations from functions in SimSET.
*/
class InputStreamFromSimSET
{
public:

    static const char * const registered_name;

    typedef std::vector<LbUsFourByte>::size_type SavedPosition;
    //! Constructor taking a stream
    /*! Data will be assumed to start at the current position reported by seekg().
      If reset() is used, it will go back to this starting position.*/
    InputStreamFromSimSET();

    ~InputStreamFromSimSET();
    //! gives method information
    std::string method_info() const;
    //! Must be called before calling for the first event.
    //! The function will try to set up first assuming that the history file
    //! is standard. Upon failure it will try with a custom set up.
    Succeeded set_up(const std::string & _history_params_filename);
    //! Check if the file is a standard history file. The code
    //! was adapted from bin.phg.c::phgrdhstStandard().
    Succeeded set_up_standard_hist_file();

    Succeeded set_up_custom_hist_file();

    inline
    Succeeded get_next_record(CListRecordSimSET& record);

    //! go back to starting position
    inline
    Succeeded reset();

    //! save current "get" position in an internal array
    inline
    SavedPosition save_get_position();
    //! set current "get" position to previously saved value
    inline
    Succeeded set_get_position(const SavedPosition&);
    //! Function that enables the user to store the saved get_positions
    inline
    std::vector<LbUsFourByte> get_saved_get_positions() const;
    //! Function that sets the saved get_positions
    inline
    void set_saved_get_positions(const std::vector<LbUsFourByte>& );

    inline unsigned long get_total_number_of_events() const;

protected:

    void set_defaults();

private:
    //! The history file we are going to process
    FILE *historyFile;
    //! History file name.
    std::string history_filename;
    //! Input header
    unique_ptr<PhoHFileHdrTy> phgrdhstHdrParams;
    //! Hook to header
    unique_ptr<LbHdrHkTy> headerHk;
    //! Type of current event.
    //! \warning This might vary in custom history files
    EventTy eventType;
    //! Current file index
    LbUsFourByte curFileIndex;
    //! Number of photons processed
    LbUsFourByte numPhotonsProcessed;
    //! Number of decays processed
    LbUsFourByte numDecaysProcessed;
    //! First event in the history file.
    LbUsFourByte startFileIndex;
    //! Total number of photons in the history file.
    LbUsFourByte numPhotons;

    std::vector<LbUsFourByte> saved_get_positions;
    //! The next decay. SimSET scans history files using
    //! a current decay and a pointer to the next decay.
    //! Very much like iterator operate. This points to the
    //! next decay event.
    PHG_Decay nextDecay;

};

END_NAMESPACE_STIR

#include "stir/IO/InputStreamFromSimSET.inl"

#endif
