# CMake generated Testfile for 
# Source directory: /root/devel/buildConda/sources/STIR/src/test/numerics
# Build directory: /root/devel/buildConda/sources/STIR/src/src/test/numerics
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_IR_filters "/root/devel/buildConda/sources/STIR/src/src/test/numerics/test_IR_filters")
set_tests_properties(test_IR_filters PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/root/devel/buildConda/sources/STIR/src/config" _BACKTRACE_TRIPLES "/root/devel/buildConda/sources/STIR/src/cmake/stir_test_exe_targets.cmake;73;ADD_TEST;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;17;create_stir_test;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;0;")
add_test(test_BSplines "/root/devel/buildConda/sources/STIR/src/src/test/numerics/test_BSplines")
set_tests_properties(test_BSplines PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/root/devel/buildConda/sources/STIR/src/config" _BACKTRACE_TRIPLES "/root/devel/buildConda/sources/STIR/src/cmake/stir_test_exe_targets.cmake;73;ADD_TEST;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;18;create_stir_test;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;0;")
add_test(test_BSplinesRegularGrid "/root/devel/buildConda/sources/STIR/src/src/test/numerics/test_BSplinesRegularGrid")
set_tests_properties(test_BSplinesRegularGrid PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/root/devel/buildConda/sources/STIR/src/config" _BACKTRACE_TRIPLES "/root/devel/buildConda/sources/STIR/src/cmake/stir_test_exe_targets.cmake;73;ADD_TEST;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;19;create_stir_test;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;0;")
add_test(test_BSplinesRegularGrid1D "/root/devel/buildConda/sources/STIR/src/src/test/numerics/test_BSplinesRegularGrid1D")
set_tests_properties(test_BSplinesRegularGrid1D PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/root/devel/buildConda/sources/STIR/src/config" _BACKTRACE_TRIPLES "/root/devel/buildConda/sources/STIR/src/cmake/stir_test_exe_targets.cmake;73;ADD_TEST;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;20;create_stir_test;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;0;")
add_test(test_erf "/root/devel/buildConda/sources/STIR/src/src/test/numerics/test_erf")
set_tests_properties(test_erf PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/root/devel/buildConda/sources/STIR/src/config" _BACKTRACE_TRIPLES "/root/devel/buildConda/sources/STIR/src/cmake/stir_test_exe_targets.cmake;73;ADD_TEST;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;21;create_stir_test;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;0;")
add_test(test_matrices "/root/devel/buildConda/sources/STIR/src/src/test/numerics/test_matrices")
set_tests_properties(test_matrices PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/root/devel/buildConda/sources/STIR/src/config" _BACKTRACE_TRIPLES "/root/devel/buildConda/sources/STIR/src/cmake/stir_test_exe_targets.cmake;73;ADD_TEST;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;22;create_stir_test;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;0;")
add_test(test_overlap_interpolate "/root/devel/buildConda/sources/STIR/src/src/test/numerics/test_overlap_interpolate")
set_tests_properties(test_overlap_interpolate PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/root/devel/buildConda/sources/STIR/src/config" _BACKTRACE_TRIPLES "/root/devel/buildConda/sources/STIR/src/cmake/stir_test_exe_targets.cmake;73;ADD_TEST;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;23;create_stir_test;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;0;")
add_test(test_integrate_discrete_function "/root/devel/buildConda/sources/STIR/src/src/test/numerics/test_integrate_discrete_function")
set_tests_properties(test_integrate_discrete_function PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/root/devel/buildConda/sources/STIR/src/config" _BACKTRACE_TRIPLES "/root/devel/buildConda/sources/STIR/src/cmake/stir_test_exe_targets.cmake;73;ADD_TEST;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;24;create_stir_test;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;0;")
add_test(test_Fourier "/root/devel/buildConda/sources/STIR/src/src/test/numerics/test_Fourier")
set_tests_properties(test_Fourier PROPERTIES  ENVIRONMENT "STIR_CONFIG_DIR=/root/devel/buildConda/sources/STIR/src/config" _BACKTRACE_TRIPLES "/root/devel/buildConda/sources/STIR/src/cmake/stir_test_exe_targets.cmake;73;ADD_TEST;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;25;create_stir_test;/root/devel/buildConda/sources/STIR/src/test/numerics/CMakeLists.txt;0;")
