#! /bin/sh
# Shell script for copying Interfile files and their headers
# Kris Thielemans 27/07/99

if [ $# -lt 2 ]; then
  echo "Usage: $0 fromfiles destination";
  echo "'fromfiles' can be specified with or without extension"
  echo "When there is more than 1 name in 'fromfiles', 'destination' has "
  echo "to be a directory.";
fi

# get last argument in a funny way
destination=`echo $* |awk '{ print $NF }'`
# test if last arg is a directory when there are more than 2 arguments
if [ $# -gt 2  -a ! -d $destination ]; then
    echo "Last argument must be a directory when giving more than 1 source";
    exit 1;
  fi

while [ $# -ge 2 ]; do

	source=$1
	# test if the files exist
	if [ ! -r $source.hv  ]; then 
	  # try to remove the extension
	  if [ -r  ${source%.*}.hv ]; then
	    source=${source%.*};
	  fi;
	fi

	filesnotfound=""
	if [ ! -r $source.v ]; then filesnotfound="$source.v"; fi
	if [ ! -r $source.hv ]; then filesnotfound="$filesnotfound $source.hv"; fi
	if [ ! -r $source.ahv ]; then filesnotfound="$filesnotfound $source.ahv"; fi
	if [ "X$filesnotfound" != "X" ]; then
	  echo "$0: file(s) $filesnotfound not found. Stopped copying $1.";
	  exit 1;
	fi

	if [ -d $destination ]; then 
	  # append the source name to destination after removal of 
	  # directory specification in source
	  currentdestination=${destination}/${source##*/};
	else
	  currentdestination=${destination}
	fi

	echo "copying $source to $currentdestination";
	cp $source.v $currentdestination.v
        # do headers. Replace $source.v with $currentdestination.v, but
        # dropping any directory specification
        # To be a bit more safe, we try to replace it only when $source.v
        # appears after "file :="
        # (supposedly as part of the "name of data file" keyword)
	inpattern="[Ff][Ii][Ll][Ee].*:=.*$source.v"
	outpattern="file := ${currentdestination##*/}.v"
	cat $source.hv | sed "s!$inpattern!$outpattern!" > $currentdestination.hv
	cat $source.ahv | sed "s!$inpattern!$outpattern!" > $currentdestination.ahv

 	# end of processing current arg
	shift;
done