!INTERFILE  :=
!imaging modality := PT
name of data file := template_span11.s
originating system := Siemens mMR
!version of keys := STIR3.0
!GENERAL DATA :=
!GENERAL IMAGE DATA :=
!type of data := PET
imagedata byte order := LITTLEENDIAN
!PET STUDY (General) :=
!PET data type := Emission
applied corrections := {None}
!number format := float
!number of bytes per pixel := 4
number of dimensions := 4
matrix axis label [4] := segment
!matrix size [4] := 11
matrix axis label [3] := view
!matrix size [3] := 252
matrix axis label [2] := axial coordinate
!matrix size [2] := { 27,49,71,93,115,127,115,93,71,49,27}
matrix axis label [1] := tangential coordinate
!matrix size [1] := 344
minimum ring difference per segment := { -60,-49,-38,-27,-16,-5,6,17,28,39,50}
maximum ring difference per segment := { -50,-39,-28,-17,-6,5,16,27,38,49,60}
Scanner parameters:= 
Scanner type := Siemens mMR
Number of rings                          := 64
Number of detectors per ring             := 504
Inner ring diameter (cm)                 := 65.6
Average depth of interaction (cm)        := 0.7
Distance between rings (cm)              := 0.40625
Default bin size (cm)                    := 0.208626
View offset (degrees)                    := 0
Maximum number of non-arc-corrected bins := 344
Default number of arc-corrected bins     := 344
Number of blocks per bucket in transaxial direction         := 1
Number of blocks per bucket in axial direction              := 2
Number of crystals per block in axial direction             := 8
Number of crystals per block in transaxial direction        := 9
Number of detector layers                                   := 1
Number of crystals per singles unit in axial direction      := 16
Number of crystals per singles unit in transaxial direction := 9
end scanner parameters:=
effective central bin size (cm) := 0.208815
number of time frames := 1
!END OF INTERFILE :=
