//
// $Id$
//
// This file is for doxygen only. It does not contain any code.

/*!
 \mainpage

 \section Introduction

 This is the documentation for the PARAPET library. It is automatically
 generated by doxygen from text comments in the files.

 As the library is rather large, some guidance is probably needed. The
 best place to start is probably the Modules section. This attempts to
 group files in a sensible way. In particular, a User is probably only
 interested in the modules which contain executables (not a library). 

 Another place to navigate through this is the Class Hierarchy page. 
 However, this is not structured at all, and even contains some classes
 which we'd rather not have in there. So, this might be more confusing 
 than anything else.

 Other information (sometimes overlapping) is given in the User's Guide, and 
 the Software Architecture sections, available on the web-site.

 \section Warnings

 Although doxygen is a wonderful tool, it does have a few problems. For
 example:
 <ul>
 <li>the #include statements do not always contain the correct path of the 
     files
 <li>Class hierarchies based on RegisteredObject et al are unfortunately not
   listed correctly. For example, doxygen does not show that
   MedianImageFilter3D is derived from ImageProcessor (through 
   RegisteredObject). This is because the derivation is done via templates.

 </ul>

*/
