# CMake generated Testfile for 
# Source directory: /root/devel/buildConda/sources/STIR/src
# Build directory: /root/devel/buildConda/sources/STIR/src/src
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("buildblock")
subdirs("numerics_buildblock")
subdirs("data_buildblock")
subdirs("recon_buildblock")
subdirs("IO")
subdirs("utilities")
subdirs("display")
subdirs("modelling_buildblock")
subdirs("listmode_buildblock")
subdirs("spatial_transformation_buildblock")
subdirs("Shape_buildblock")
subdirs("eval_buildblock")
subdirs("scatter_buildblock")
subdirs("scatter_utilities")
subdirs("modelling_utilities")
subdirs("listmode_utilities")
subdirs("analytic/FBP2D")
subdirs("analytic/SRT2D")
subdirs("analytic/SRT2DSPECT")
subdirs("analytic/FBP3DRP")
subdirs("iterative/OSMAPOSL")
subdirs("iterative/KOSMAPOSL")
subdirs("iterative/OSSPS")
subdirs("iterative/POSMAPOSL")
subdirs("iterative/POSSPS")
subdirs("SimSET")
subdirs("SimSET/scripts")
subdirs("test")
subdirs("test/numerics")
subdirs("test/modelling")
subdirs("swig")
