#=====================================================

#  P A R T I C L E   S O U R C E

#=====================================================

/gate/source/addSource                                         posiFDG



/gate/source/posiFDG/setType backtoback



# The particles emitted by the source are gammas

/gate/source/posiFDG/gps/particle gamma



# The gammas have an energy of 511 keV

/gate/source/posiFDG/gps/energytype Mono

/gate/source/posiFDG/gps/monoenergy 0.511 MeV



/gate/source/posiFDG/setActivity                               5000000 becquerel



/gate/source/posiFDG/setForcedUnstableFlag                     true

/gate/source/posiFDG/setForcedHalfLife                         6586 s

/gate/source/posiFDG/gps/angtype                               iso


#Shape of the source
/gate/source/posiFDG/gps/type Point

#Position of the source
/gate/source/posiFDG/gps/centre 19. 0. 7. cm

/gate/source/list
