//
// $Id$
//
// This file is for doxygen only. It does not contain any code.
/*
    Copyright (C) 2000- $Date$, IRSL
    See STIR/LICENSE.txt for details
*/

/*!
 \mainpage

 \section intro Introduction

 This is the documentation for STIR: Software for Tomographic
 Image Reconstruction. It is automatically
 generated by doxygen from text comments in the files.

 As the amount of software is rather large, some guidance is probably 
 needed. The best place to start is probably the Modules section. This
 attempts to group files in a sensible way. In particular, a User is
 probably only interested in the modules which contain executables 
 (not a library). 

 Another way to navigate through this is the Class Hierarchy page, or indeed
 any of the other alphabetical lists. 
 However, this is not structured at all, and even contains some classes
 which we'd rather not have in there. So, in the beginning, this might be 
 somewhat confusing.

 Other information (sometimes overlapping) is given in the User's Guide, and 
 the Software Architecture sections, available on the web-site.

 \section docproblems Problems to keep in mind when reading this documentation

 All documentation depends on the person who writes it. In the end, only 
 the code is what matters...


 Although doxygen is a wonderful tool, it does have a few problems. For
 example:
 <ul>
 <li>the #include statements do not always contain the correct path of the 
     files
 <li>Class hierarchies based on RegisteredObject et al are unfortunately not
   always listed correctly. However, with the current hierarchies, this 
   problem shows up in only a few places.  For example, the class
   hierarchies of most of the ImageProcessor classes are incomplete on their
   own documentation page. However, they are fine in the main
   'class hierarchy' page.
 </ul>

*/
