!INTERFILE  :=
name of data file := test_projdata.s
originating system := ECAT 962
!version of keys := STIR6.0
!GENERAL DATA :=
!GENERAL IMAGE DATA :=
!type of data := PET
imagedata byte order := LITTLEENDIAN
number of radionuclides := 1
!PET STUDY (General) :=
!PET data type := Emission
applied corrections := {arc correction}
!number format := float
!number of bytes per pixel := 4
number of dimensions := 4
matrix axis label [4] := segment
!matrix size [4] := 7
matrix axis label [3] := view
!matrix size [3] := 8
matrix axis label [2] := axial coordinate
!matrix size [2] := { 47,53,59,63,59,53,47}
matrix axis label [1] := tangential coordinate
!matrix size [1] := 6
minimum ring difference per segment := { -9,-7,-4,-1,2,5,8}
maximum ring difference per segment := { -8,-5,-2,1,4,7,9}
Scanner parameters:=
  Scanner type := ECAT 962
  Number of rings                          := 32
  Number of detectors per ring             := 576
  Inner ring diameter (cm)                 := 82.4
  Average depth of interaction (cm)        := 0.7
  Distance between rings (cm)              := 0.485
  Default bin size (cm)                    := 0.225
  View offset (degrees)                    := 0
  Maximum number of non-arc-corrected bins := 288
  Default number of arc-corrected bins     := 288
  Energy resolution         := 0
  Reference energy (in keV) := 511
  Number of blocks per bucket in transaxial direction         := 3
  Number of blocks per bucket in axial direction              := 4
  Number of crystals per block in axial direction             := 8
  Number of crystals per block in transaxial direction        := 8
  Number of detector layers                                   := 1
  Number of crystals per singles unit in axial direction      := 8
  Number of crystals per singles unit in transaxial direction := 24
  Scanner geometry (BlocksOnCylindrical/Cylindrical/Generic)  := Cylindrical
End scanner parameters:=
effective central bin size (cm) := 0.225
number of time frames := 1
start vertical bed position (mm) := 0
start horizontal bed position (mm) := 0
!END OF INTERFILE :=
