name: Build PETSIRD + STIR

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    stir-with-petsird:
        runs-on: ubuntu-24.04

        env:
            PETSIRD_PREFIX: ${{ github.workspace }}/petsird-install
        
        steps:
        - name: Install System Dependencies (date-tz)
          run: |
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y universe
            sudo apt-get update
            sudo apt install -y libomp-dev libboost-dev libhdf5-serial-dev nlohmann-json3-dev
            sudo apt-get install -y libdate-tz-dev || sudo apt-get install -y libhowardhinnant-date-dev
            # sudo apt-get install -y libopenblas-dev 

        - name: Checkout STIR
          uses: actions/checkout@v4

        - name: Checkout PETSIRD
          uses: actions/checkout@v4
          with:
            repository: NikEfth/PETSIRD
            ref: fix/cmake-export
            path: PETSIRD
            
        - name: Checkout Yardl (main)
          uses: actions/checkout@v4
          with:
            repository: microsoft/yardl
            ref: main
            path: yardl
            
        - name: Setup micromamba (yardl env)
          uses: mamba-org/setup-micromamba@v2
          with:
            environment-file: yardl/environment.yml
            activate-environment: yardl
        
        - name: Export CMake prefix path
          run: |
            echo "CMAKE_PREFIX_PATH=$CONDA_PREFIX;$CMAKE_PREFIX_PATH" >> $GITHUB_ENV

        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.22'

        - name: Build and install Yardl
          run: |
            cd yardl/tooling/cmd/yardl
            go build
            mkdir -p "$HOME/.local/bin"
            install -m 755 yardl $HOME/.local/bin/yardl
            echo "$HOME/.local/bin" >> $GITHUB_PATH
            "$HOME/.local/bin/yardl" --version

        - name: Install just
          run: |
            sudo apt-get update
            sudo apt-get install -y cmake ninja-build just

        - name: Install PETSIRD Python dependencies
          run: |
            micromamba install -y -n yardl -f PETSIRD/environment.yml
            micromamba install -n yardl -c conda-forge xtensor xtensor-blas openblas
        #     micromamba install -y -n yardl -c conda-forge libdate tzdata libcurl

        - name: Generate PETSIRD sources (yardl) 
          run: |
            micromamba run -n yardl bash -lc "
            export CC=/usr/bin/gcc
            export CXX=/usr/bin/g++
            
            # Make conda packages visible to CMake
            export CMAKE_PREFIX_PATH=\$CONDA_PREFIX:\$CMAKE_PREFIX_PATH
            export CXXFLAGS=\"-I\$MAMBA_ROOT_PREFIX/envs/yardl/include \$CXXFLAGS\"

            cd PETSIRD/model
            just build
            "
        - name: Build PETSIRD C++
          run: |
            micromamba run -n yardl bash -lc "
            cd PETSIRD/cpp
            mkdir -p build 
            cd build
            
            cmake .. \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_PREFIX_PATH=\"\$CONDA_PREFIX\" \
                -DCMAKE_INSTALL_PREFIX=\"${{ env.PETSIRD_PREFIX }}\"

            cmake --build . --target install -- -j$(nproc)
            "

        - name: Fix yardl mistake
          run: |
            FILE="PETSIRD/cpp/generated/petsird/CMakeLists.txt"
            echo "🔧 Fixing yardl-generated CMakeLists.txt (removing xtensor linkage)"
            sed -i.bak \
            -e '/^[[:space:]]*xtensor[[:space:]]*$/d' \
            "$FILE"


        - name: Build STIR with PETSIRD
          run: |
            micromamba run -n yardl bash -e <<'EOF'
            export CC=/usr/bin/gcc
            export CXX=/usr/bin/g++
            export CMAKE_PREFIX_PATH="$CONDA_PREFIX:${PETSIRD_PREFIX}"
            
            mkdir -p build-stir
            cd build-stir
            
            cmake .. \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_PREFIX_PATH=\"\$CMAKE_PREFIX_PATH\" \
                -DPETSIRD_DIR=\"${{ env.PETSIRD_PREFIX }}/lib/cmake/PETSIRD\" \
                -DDISABLE_PETSIRD:BOOL=OFF \
                -DDISABLE_HDF5:BOOL=OFF \
                -DDISABLE_NLOHMANN_JSON:BOOL=OFF\
                -DSTIR_OPENMP:BOOL=ON
            
            cmake --build . -- -j$(nproc)
            EOF








        